apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owner
spec:
  tls:
  - hosts:
    - owner.fido.gracey.dev
    secretName: owner-tls
  rules:
  - host: owner.fido.gracey.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: owner
            port:
              number: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: owner-tls
spec:
  secretName: owner-tls
  dnsNames:
    - owner.fido.gracey.dev
  issuerRef:
    name: letsencrypt-gracey-dev
    kind: ClusterIssuer